 go get github.com/uudashr/gopkgs/cmd/gopkgs
 go get github.com/ramya-rao-a/go-outline
 go get github.com/acroca/go-symbols
 go get golang.org/x/tools/cmd/guru
 go get golang.org/x/tools/cmd/gorename
 go get github.com/stamblerre/gocode
 go get github.com/rogpeppe/godef
 go get github.com/ianthehat/godef
 go get github.com/sqs/goreturns
 go get golang.org/x/lint/golint